version: '3.7'

services:
  
  db:
    image: kartoza/postgis:12.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment: 
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
    ports:
      - 5432:5432
    restart: always
  
    
  web:
    build: .
    command: bash -c "while !</dev/tcp/db/5432; do sleep 1; done; python manage.py makemigrations && python manage.py migrate && python manage.py fixture && python manage.py runserver 0.0.0.0:8000" 
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
     

volumes:
  postgres_data: